server:
  port: 8082
  session:
    cookie:
      name: UISESSION         
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId : ClientId
      clientSecret : secret
      accessTokenUri : http://localhost:9000/auth/oauth/token
      userAuthorizationUri : http://localhost:9000/auth/oauth/authorize 
    resource:
      userInfoUri : http://localhost:9000/auth/rest/hello/principal    
spring:
  thymeleaf: 
    cache : false
        